version: '3.8'

services:
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - estoque_default
    depends_on:
      - mysql_existing

  nginx:
    container_name: laravel_nginx
    image: nginx:1.27-alpine
    ports:
      - "4002:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - estoque_default
    depends_on:
      - app

  # Alias para acessar o MySQL existente
  mysql_existing:
    image: mysql:8.0
    container_name: mysql_alias_only
    networks:
      - estoque_default
    external_links:
      - mysql_db:mysql_db
    command: ["true"] # n√£o roda MySQL, apenas "representa" o link

networks:
  estoque_default:
    external: true
