services:
  app:
    container_name: laravel_app_barber
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    networks:
      - apolonet
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_DATABASE: barber
      DB_USERNAME: root
      DB_PASSWORD: root

    

  nginx:
    container_name: laravel_nginx
    image: nginx:1.27-alpine
    ports:
      - "4002:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - apolonet
    depends_on:
      - app

networks:
  apolonet:
    external: true
